name: Lambaa Release

on:
    push:
        branches: master
        paths:
            - "src/**"
            - "package.json"
            - "package-lock.json"

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0
            - uses: actions/setup-node@v2
            - name: Generate tag name
              id: tag_name
              run: echo "::set-output name=value::$(node -e 'console.log(require("./package.json").version)')"
            - uses: johnyherangi/release-notes@master
              id: release_notes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                  tag_name: ${{ steps.tag_name.outputs.value }}
                  release_name: ${{ steps.release_notes.outputs.release_name }}
                  body: ${{ steps.release_notes.outputs.release_notes }}